# Generated by Django 3.0 on 2022-11-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_packagetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetag',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagetag_package', to='base.Package'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edition_package', to='base.Package'),
        ),
        migrations.AlterUniqueTogether(
            name='packagetag',
            unique_together={('key', 'value', 'package')},
        ),
    ]
